# Basic
markdown: kramdown
title: Dark`Kris
subtitle: Private blog
description: I'm spark , hope you fire
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ç‹ç† å¼˜
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Reign in Hell
url: "http://darkkris.github.io"

# Comment
comment:
    # disqus: DarkKris
    # duoshuo: DarkKris
    # cloudTie: DarkKris

# Social
social:
    weibo: DarkKris 
    github: DarkKris
    twitter: long4664030
    mail: long4664030@163.com
    gplus: 105038708474545427650

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
# baidu:
#     id:94bd6d5efd92345bf72bd9c19bd16f49

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: UA-102043025-1   
#     host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


